"""Shared protocol constants for Bloxx node ↔ server communication."""

APP_NAME = "bloxx"
NODE_ASPECT = "node"
SERVER_ASPECT = "server"
VERSION = "0.1.0"

# RNS request handler paths
PATH_CMD = "/cmd"
PATH_TELEMETRY = "/telemetry"
PATH_CONFIG = "/config"
PATH_TIME = "/time"

# Command names
CMD_GET_CONFIG = "get_config"
CMD_PUT_CONFIG = "put_config"
CMD_PATCH_CONFIG = "patch_config"
CMD_GET_TIME = "get_time"
CMD_TELEMETRY = "telemetry"
CMD_SVC_RESTART = "svc_restart"
CMD_SVC_STOP = "svc_stop"
CMD_SVC_START = "svc_start"
CMD_WIFI_SET = "wifi_set"
CMD_IFACE_SET = "iface_set"
CMD_RNODE_RESET = "rnode_reset"
CMD_RNODE_UPDATE = "rnode_update"
CMD_RNS_ANNOUNCE = "rns_announce"
CMD_LOG_PULL = "log_pull"
CMD_DISK_CLEANUP = "disk_cleanup"
CMD_CONNECTIVITY_CHECK = "connectivity_check"
CMD_AGENT_UPDATE = "agent_update"
CMD_SHUTDOWN = "shutdown"
CMD_REBOOT = "reboot"
CMD_SHUTDOWN_THRESHOLD = "shutdown_threshold"

# Config types
CFG_RNS = "rns"
CFG_AGENT = "agent"
CFG_SYSTEM = "system"

# Error codes reported in telemetry
ERR_BATT_CRITICAL = "batt_critical"
ERR_BATT_SENSOR_UNAVAIL = "batt_sensor_unavail"
ERR_DISK_FULL = "disk_full"
ERR_TEMP_CRITICAL = "temp_critical"
ERR_CONFIG_APPLY_FAILED = "config_apply_failed"
ERR_CONFIG_ROLLBACK = "config_rollback"
ERR_RNODE_UPDATE_FAILED = "rnode_update_failed"
ERR_RNODE_USB_RESET = "rnode_usb_reset"
ERR_RNODE_RESTART = "rnode_restart"
ERR_FS_READONLY = "fs_readonly"
ERR_FS_ERRORS = "fs_errors"
ERR_OOM_KILLED = "oom_killed"
ERR_WATCHDOG_REBOOT = "watchdog_reboot"
ERR_NO_PEERS = "no_peers"
ERR_INTERFACE_DOWN = "interface_down"
ERR_LOAD_HIGH = "load_high"
ERR_SWAP_HIGH = "swap_high"
ERR_NO_CHARGING = "no_charging"
